BloomBuddy/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    text = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

BloomBuddy/blog_posts/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from BloomBuddy import db
from BloomBuddy.models import BlogPost, Comment
from BloomBuddy.blog_posts.forms import BlogPostForm, CommentForm
from flask import abort
from sqlalchemy import or_

blog_posts = Blueprint('blog_posts', __name__)


# Create


@blog_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)


# Blog post(Read and Add Comments)


# @blog_posts.route('/<int:blog_post_id>', methods=['GET', 'POST'])
# def blog_post(blog_post_id):
#  blog_post = BlogPost.query.get_or_404(blog_post_id)
#  form = CommentForm()
#  comments = blog_post.comments.order_by(Comment.timestamp.desc()).all()
#  if form.validate_on_submit():
#     comment = Comment(text=form.text.data, post=blog_post, user_id=current_user.id)
#      db.session.add(comment)
#     db.session.commit()
#     flash('Your comment has been added to the post', 'success')
#    return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
# return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post, form=form, comments=comments)

@blog_posts.route('/<int:blog_post_id>', methods=['GET', 'POST'])
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    form = CommentForm()
    comments = blog_post.comments.order_by(Comment.timestamp.asc()).all()
    if form.validate_on_submit():
        parent_id = request.form.get('parent_id')
        if parent_id:
            parent_comment = Comment.query.get_or_404(parent_id)
            reply = Comment(text=form.text.data, post_id=blog_post_id, users_id=current_user.id)
            parent_comment.replies.append(reply)
            flash('Your reply has been added to the comment', 'success')
        else:
            comment = Comment(text=form.text.data, post_id=blog_post_id, users_id=current_user.id)
            db.session.add(comment)
            flash('Your comment has been added to the post', 'success')
        db.session.commit()
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post, form=form,
                           comments=comments)


# Delete Comment


@blog_posts.route('/delete_comment/<int:comment_id>', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not current_user.is_admin and comment.users_id != current_user.id:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('The comment has been deleted', 'success')
    return redirect(url_for('blog_posts.blog_post', blog_post_id=comment.post_id))


# Update


@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if not current_user.is_admin and blog_post.author != current_user:
        abort(403)
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Updating', form=form)


# Delete


@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if not current_user.is_admin and blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))

# Search


@blog_posts.route('/search')
def search():
    query = request.args.get('q')
    if query is not None:
        blog_posts = BlogPost.query.filter(or_(BlogPost.title.contains(query), BlogPost.text.contains(query))).all()
    else:
        blog_posts = []
    return render_template('search.html', blog_posts=blog_posts)


# Reply


@blog_posts.route('/<int:blog_post_id>/reply', methods=['POST'])
@login_required
def add_reply(blog_post_id):
    form = CommentForm()
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    comments = blog_post.comments.order_by(Comment.timestamp.desc()).all()
    if form.validate_on_submit():
        parent_id = request.form.get('parent_id')
        parent_comment = Comment.query.get_or_404(parent_id)
        reply = Comment(text=form.text.data, post_id=blog_post_id, user_id=current_user.id)
        parent_comment.replies.append(reply)
        db.session.commit()
        flash('Your reply has been added to the comment', 'success')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post_id))
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post, form=form,
                           comments=comments)

BloomBuddy/core/views.py
from flask import render_template, request, Blueprint
from BloomBuddy.models import BlogPost

core = Blueprint('core', __name__)


@core.route('/')
def home():
    return render_template('home.html')


@core.route('/blogs')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', blog_posts=blog_posts, current_url=request.path)


@core.route('/info')
def info():
    return render_template('info.html')

BloomBuddy/users/views.py
# users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify, abort
from flask_login import login_user, current_user, logout_user, login_required
from BloomBuddy import db
from BloomBuddy.models import User, BlogPost, Plant
from BloomBuddy.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from BloomBuddy.users.picture_handler import add_profile_pic
from werkzeug.security import generate_password_hash

users = Blueprint('users', __name__)


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data,
                    is_admin=form.is_admin.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Log in Success!')
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.home')
            return redirect(next)
    return render_template('login.html', form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.home"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    plants = Plant.query.filter_by(user_id=current_user.id).all()
    users = None
    if current_user.is_admin:
        users = User.query.order_by(User.username).all()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        if form.password.data:
            current_user.password_hash = generate_password_hash(form.password.data)
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form, plants=plants, users=users)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user) \
        .order_by(BlogPost.date.desc()) \
        .paginate(page=page, per_page=5)
    plants = Plant.query.filter_by(user_id=user.id).all()
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user, plants=plants)


@users.route('/save_plants', methods=['POST'])
@login_required
def save_plants():
    data = request.get_json()
    for plant in data['plants']:
        new_plant = Plant(name=plant['name'], age=plant['age'], health=plant['health'], user_id=current_user.id)
        db.session.add(new_plant)
    db.session.commit()
    return jsonify({'message': 'Plants saved successfully'}), 200

@users.route('/delete_plant/<int:plant_id>', methods=['DELETE'])
@login_required
def delete_plant(plant_id):
    plant = Plant.query.get_or_404(plant_id)
    if plant.user_id != current_user.id:
        abort(403)
    db.session.delete(plant)
    db.session.commit()
    return jsonify({'message': 'Plant deleted successfully'}), 200

@users.route('/delete_user/<int:user_id>', methods=['DELETE'])
@login_required
def delete_user(user_id):
    if not current_user.is_admin:
        abort(403)
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    return jsonify({'message': 'User deleted successfully'}), 200

BloomBuddy/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
            crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/tpk2upgmi1dsraw6j6g8wwqh0hvuqtu7w82d920bxlwgmsmn/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>
    <link rel="icon" href="{{ url_for('static', filename='Logo.png') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> BloomBuddy </title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" aria-current="page" href="{{url_for('core.home')}}">Home</a>
                <a class="nav-link" aria-current="page" href="{{url_for('core.index')}}">Blogs</a>
                <a class="nav-link" aria-current="page" href="{{url_for('core.info')}}">About</a>
                {% if current_user.is_authenticated %}
                <a class="nav-link" aria-current="page" href="{{url_for('users.logout')}}">Log Out</a>
                <a class="nav-link" aria-current="page" href="{{url_for('users.account')}}">Account</a>
                {% if current_url == '/blogs' %}
                <a class="nav-link" aria-current="page" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
                {% endif %}
                {% else %}
                <a class="nav-link" aria-current="page" href="{{url_for('users.login')}}">Log In</a>
                <a class="nav-link" aria-current="page" href="{{url_for('users.register')}}">Register</a>
                {% endif %}
            </div>
        </div>
        {% if current_url == '/blogs' %}
        <nav class="navbar bg-body-tertiary">
            <div class="ms-auto">
                <form class="d-flex" action="{{url_for('blog_posts.search')}}" role="search" method="get">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </nav>
        {% endif %}
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

BloomBuddy/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="bg-light p-5">
    <h1>{{post.title}}</h1>
    <h2>Written by: {{post.author.username}}</h2>
    <h3>Published: {{post.date.strftime('%B %d, %Y')}}</h3>
    <p>{{ post.text|safe }}</p>

    {% if current_user.is_authenticated and (post.author == current_user or current_user.is_admin) %}
    <div>
        <a href="{{url_for('blog_posts.update', blog_post_id=post.id)}}">Update</a>
        <button type="button" class="btn btn-danger" data-bs-toggle='modal' data-bs-target="#del_modal">Delete</button>
    </div>
    {%endif%}

    <div class="modal" tabindex="-1" id="del_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete post?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete the post?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <form action="{{url_for('blog_posts.delete_post', blog_post_id=post.id)}}" method="POST">
                        <input type="submit" value="Delete" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% macro render_comment(comment) %}
<div class="comment">
    <p><a href="{{ url_for('users.user_posts', username=comment.user.username) }}">{{ comment.user.username }}</a> : {{
        comment.text }}</p>
    {% if current_user.is_authenticated and (comment.users_id == current_user.id or current_user.is_admin) %}
    <p>
    <form action="{{ url_for('blog_posts.delete_comment', comment_id=comment.id) }}" method="post">
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
    </p>
    {% endif %}
    <button class="reply-button btn btn-primary">Reply</button>
    <form class="reply-form" action="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" method="post"
          style="display: none;">
        <input type="hidden" name="parent_id" value="{{ comment.id }}">
        {{ form.text }}
        {{ form.submit }}
    </form>
    <div class="replies">
        {% for reply in comment.replies %}
        {{ render_comment(reply) }}
        {% endfor %}
    </div>
</div>
{% endmacro %}
{% for comment in comments %}
{{ render_comment(comment) }}
{% endfor %}

<div class="comments-section">
    {% if current_user.is_authenticated %}
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.text(class="large-input", placeholder="Comment") }}
        {{ form.submit(class="btn btn-success") }}
    </form>
    {% else %}
    <p>You must be logged in to post a comment.</p>
    {% endif %}
</div>

<script>
    document.querySelectorAll('.reply-button').forEach(function(button) {
        button.addEventListener('click', function() {
            var form = this.nextElementSibling;
            form.style.display = form.style.display === 'none' ? 'block' : 'none';
        });
    });
</script>
{% endblock %}

BloomBuddy/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <form class="form-group" method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.title.label(class = "form-control-label")}}
            {{form.title(class ="form-control form-control-lg")}}
        </div>
        <div class="form-group">
            {{form.text.label(class = "form-control-label")}}
            {{form.text(class ="form-control form-control-lg", id='my_textarea', required=False)}}
        </div>
        <div class="form-group">
            {{form.submit(class = "btn btn-outline-info")}}
        </div>
    </form>
</div>
<script>
    tinymce.init({
        selector: '#my_textarea',
        plugins: 'image link autoresize charmap print preview hr anchor pagebreak',
        toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | image | link | charmap | print | preview | hr | anchor | pagebreak',
        automatic_uploads: true,
        images_upload_handler: function (blobInfo, success, failure) {
            var xhr, formData;

            xhr = new XMLHttpRequest();
            xhr.withCredentials = false;
            xhr.open('POST', '/upload_image');

            xhr.onload = function() {
                var json;

                if (xhr.status != 200) {
                    failure('HTTP Error: ' + xhr.status);
                    return;
                }

                json = JSON.parse(xhr.responseText);

                if (!json || typeof json.location != 'string') {
                    failure('Invalid JSON: ' + xhr.responseText);
                    return;
                }

                success(json.location);
            };

            formData = new FormData();
            formData.append('file', blobInfo.blob(), blobInfo.filename());

            xhr.send(formData);
        },
    });
</script>
{% endblock %}

BloomBuddy/templates/home.html
{% extends "base.html" %}
{%block content%}
<body class="home-background">
<div>
    <h1>Home Page</h1>
</div>
</body>
{% endblock %}

BloomBuddy/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="bg-light p-5">
    <h1>BloomBuddy Blogs</h1>
</div>

<div class="container">
    {% for post in blog_posts.items%}
    <div class="card">
        <div class="card-body">
            <h2><a class="card-title"
                   href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">{{post.title}}</a></h2>
            <a href="{{url_for('users.user_posts', username=post.author.username)}}">Written by:
                {{post.author.username}}</a>
            <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
            <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}">Read Blog
                Post</a>
        </div>
    </div>
    {%endfor%}
</div>
<nav aria-label='Page Nav'>
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class='page-item disabled'>
            <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
            <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock %}

BloomBuddy/templates/info.html
{% extends "base.html" %}
{%block content%}
<div class="bg-light p-5">
    <h1>BloomBuddy Information</h1>
</div>
<div>
    <p>Într-o epocă în care timpul este prețios și mulți dintre noi tindem să fim mai conectați la lumea digitală,
        BloomBuddy ne oferă o soluție simplă și eficientă pentru a ne asigura că plantele noastre sunt întotdeauna în
        formă optimă. Nu mai este nevoie să ne îngrijorăm că uităm să le udăm sau să ne întrebăm dacă le oferim
        suficientă atenție. Cu BloomBuddy, avem un partener de încredere care ne reamintește când este momentul să
        intervenim pentru a ne asigura că plantele noastre înfloresc în toată splendoarea lor. Folosind tehnologia de
        ultimă generație, aplicația monitorizează umiditatea solului și oferă recomandări personalizate de îngrijire,
        adaptate fiecărei specii de plantă.

        Mai mult decât atât, BloomBuddy ne oferă oportunitatea de a comunica cu alți iubitori de plante prin intermediul
        platformei sale interactive. Astfel, putem împărtăși experiențe, sfaturi și trucuri, și putem învăța unii de la
        alții cum să avem grijă mai bine de prietenii noștri verzi. Comunitatea BloomBuddy este un loc unde pasionații
        de grădinărit, fie ei începători sau experți, pot găsi suport și inspirație, creând legături și prietenii bazate
        pe dragostea comună pentru natură.

        Cu o interfață prietenoasă și ușor de utilizat, BloomBuddy transformă grădinăritul într-o activitate plăcută și
        simplă, accesibilă tuturor </p>
</div>
{% endblock %}

BloomBuddy/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="col-md-4">
        <div class="bg-light p-5 rounded shadow">
            <h1 class="text-center">Login</h1>
            <form method="POST">
                {{form.hidden_tag()}}
                <div class="mb-3">
                    {{form.email.label(class="form-label")}}
                    {{ form.email(id="InputEmail1", class="form-control") }}
                </div>
                <div class="mb-3">
                    {{form.password.label(class="form-label")}}
                    {{form.password(id="InputPassword1", class="form-control")}}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <br>
            <p class="text-center">Don't have an account? <a href="{{ url_for('users.register') }}">Click here</a></p>
        </div>
    </div>
</div>
{% endblock %}

BloomBuddy/templates/search.html
{% extends "base.html" %}
{% block content %}
<h1>Search Results for "{{ request.args.get('q') }}"</h1>
{% for post in blog_posts %}
<h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{ post.title }}</a></h2>

{% endfor %}
{% if not blog_posts %}
<p>No results found.</p>
{% endif %}
{% endblock %}

BloomBuddy/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="bg-light p-5">
        <div align='center'>
            <h1>Profile {{user.username}}</h1>
            <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
        </div>
    </div>
</div>
<div class="container">
    <select id="display-option" class="form-control">
        <option value="blogs">Blogs</option>
        <option value="plants">Plants</option>
    </select>

    <div id="blogs" class="container">
        {% for post in blog_posts.items %}
        <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
        Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
        <p class='text-muted'>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
        <br>
        <p>{{post.text|safe}}</p>
        <br>
        {% endfor %}
    </div>
    <div id="plants" class="container" style="display: none;">
        <div class="container">
            <h2>{{user.username}}'s Plants</h2>
            <table id="plants-table" class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Health</th>
                </tr>
                </thead>
                <tbody>
                {% for plant in plants %}
                <tr>
                    <td>{{ plant.name }}</td>
                    <td>{{ plant.age }}</td>
                    <td>{{ plant.health }}</td>
                    <td>
                        <button class="btn btn-danger delete-plant">Delete</button>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if user.username == current_user.username %}
            <button id="add-plant" class="btn btn-primary">Add Plant</button>
            <button id="save-plant" class="btn btn-primary">Save</button>
            {% endif %}
        </div>
    </div>
</div>
<nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class='page-item disabled'>
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{
                page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{
                page_num}}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
</div>
{% block scripts %}
<script>
    document.getElementById('display-option').addEventListener('change', function() {
        var selectedOption = this.value;
        if (selectedOption === 'blogs') {
            document.getElementById('blogs').style.display = 'block';
            document.getElementById('plants').style.display = 'none';
        } else if (selectedOption === 'plants') {
            document.getElementById('blogs').style.display = 'none';
            document.getElementById('plants').style.display = 'block';
        }
    });
</script>

<script>
    document.getElementById('add-plant').addEventListener('click', function() {
        var table = document.getElementById('plants-table');
        var row = table.insertRow(-1);
        var nameCell = row.insertCell(0);
        var ageCell = row.insertCell(1);
        var healthCell = row.insertCell(2);

        nameCell.innerHTML = '<input type="text" class="form-control" placeholder="Plant Name">';
        ageCell.innerHTML = '<select class="form-control"><option>Young</option><option>Mature</option><option>Old</option></select>';
        healthCell.innerHTML = '<select class="form-control"><option>Healthy</option><option>Unhealthy</option></select>';
    });

    document.getElementById('save-plant').addEventListener('click', function() {
        var table = document.getElementById('plants-table');
        var plants = [];
        for (var i = 1, row; row = table.rows[i]; i++) {
            if (row.cells[0].children[0] && 'value' in row.cells[0].children[0] &&
                row.cells[1].children[0] && 'value' in row.cells[1].children[0] &&
                row.cells[2].children[0] && 'value' in row.cells[2].children[0]) {
                var plant = {
                    'name': row.cells[0].children[0].value,
                    'age': row.cells[1].children[0].value,
                    'health': row.cells[2].children[0].value
                };
                plants.push(plant);
            }
        }
        fetch('/save_plants', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({'plants': plants})
        }).then(function(response) {
            return response.json();
        }).then(function(data) {
            alert(data.message);
        });
    });
        document.getElementById('plants-table').addEventListener('click', function(e) {
        if (e.target && e.target.classList.contains('delete-plant')) {
            e.target.closest('tr').remove();
        }
    });
</script>
{% endblock %}
{% endblock %}